# Generated by Django 5.2 on 2025-05-06 07:30

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_report_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to=users.models.report_photo_upload_path),
        ),
        migrations.AlterField(
            model_name='report',
            name='videos',
            field=models.FileField(blank=True, null=True, upload_to=users.models.report_video_upload_path),
        ),
    ]
